---
title: "Data analysis of salary of hire staff in Macul municipality"
author: "Jorge Cortés-Miranda"
format: html
editor: visual
---

# Salary data of hire staff in Macul municipality

In a previous step we obtained all the data related to salary of the Macul municipality only for the hired staff. After a cleaning process, we can now work with that data in order to get some insights about the salary of hire staff between 2013 and 2022. First let's load the data.

```{python}
import pandas as pd

contrata_2013_2022_clean = pd.read_csv("../data/contrata_2013_2022_clean.csv")

contrata_2013_2022_clean.info()
```

In a first exploratory analysis we could visualize the salary without discounts and his distribution over the time.

```{python}
import seaborn as sns
import matplotlib.pyplot as plt

sal_dist = sns.displot(data=contrata_2013_2022_clean, x='r_bruta_mens', hue='año', kind='kde')

sal_dist.set(xlabel = "Renta bruta mensualizada",
             ylabel = "Densidad",
             title= "Distribución de renta bruta")

plt.show()
```

We can see that the salary data is around \$1 million chilean pesos.

We can obtain some metrics about the data using the following.

```{python}
contrata_2013_2022_clean['r_bruta_mens'].describe()
```

The mean of the salary data between 2013 and 2022 is around **\$1.395.454** but with a standard deviation of **\$801.696**, we could segment this data per year and per estate and visualize it. First, let's segment it by year.

Another relevant issue is that in some cases the salary is equal to zero, let's look that.

```{python}
# first let's store this data in a new dataframe
zero_salary = contrata_2013_2022_clean[contrata_2013_2022_clean['r_bruta_mens']==0]

zero_salary["id"].unique().size

```

We know that 41 workers in some month has received \$0, let's see what percentage of workers represents that.

```{python}
percentage_zero = (zero_salary["id"].unique().size/contrata_2013_2022_clean["id"].unique().size)*100

percentage_zero
```

Those workers represents around the 10% of the total. Now we could try to know in which months this happen more frequently.

```{python}
month_freq = sns.countplot(data=zero_salary, x="Mes",
                          order = zero_salary["Mes"].value_counts().index)

```

We can observe that September is the month with most employees with zero salary.

Another question that we could try to answer is how is the distribution of salary among the years. We can visualize it using a boxplot graph.

```{python}
sns.boxplot(data=contrata_2013_2022_clean, x='año', y='r_bruta_mens', color='green')

ax.set(xlabel = "Año",
       ylabel = "R. bruta mensualizada",
       title = "Distribución de salario en el tiempo")
plt.show()
```

We observe an increment in the salary in time. Now let's segment it by estate.

```{python}
sns.boxplot(data=contrata_2013_2022_clean, x='Estamento', y='r_bruta_mens', color='red')
plt.show()
```

We observe that the estate with better salary is "Directivo" and that the "Profesional" show a greater variation.

We could try to perform an anova test in order to identify if there is statistical differences in salary between the different staments.
