---
title: "Contrata_macul"
author: "Jorge Cortés-Miranda"
format: html
editor: visual
---

## Data cleaning

The data obtained from [Portal de transparencia](https://www.portaltransparencia.cl/PortalPdT/directorio-de-organismos-regulados/?org=MU161#) from Chile, has a lot of different problems to solve before the data analysis, first we will look at the contrata payment information of the Macul munnicipality between the years 2013 and 2022.

```{python}
import pandas as pd

contrata_2013_2022 = pd.read_csv("../data/contrata_2013_2022.csv")

contrata_2013_2022.info()
```

We have 21 fields in the dataframe, but the names of the fields are very long or difficult to work with, so we will rename those.

```{python}
contrata_2013_2022.rename(
  columns = {
    "Año"                                      : "año",
    "mes"                                      : "mes",
    "Nombre.completo"                          : "nombre",
    "Cargo.o.función"                          : "cargo_funcion",
    "Grado.EUS.o.jornada"                      : "grado_jornada",
    "Calificación.profesional.o.formación"     : "calif_form",
    "Región"                                   : "region",
    "Asignaciones.especiales"                  : "as_espec",
    "Remuneración.bruta.mensualizada"          : "r_bruta_mens",
    "Remuneración.líquida.mensualizada"        : "r_liquida_mens",
    "Remuneraciones.adicionales"               : "r_adic",
    "Remuneración.Bonos.incentivos"            : "r_bonos_inc",
    "Derecho.a.horas.extraordinarias"          : "der_hr_ext",
    "Montos.y.horas.extraordinarias.diurnas"   : "mont_hr_ext_diur",
    "Montos.y.horas.extraordinarias.nocturnas" : "mont_hr_ext_noct",
    "Montos.y.horas.extraordinarias.festivas"  : "mont_hr_ext_fest",
    "Fecha.de.inicio.dd.mm.aa"                 : "fecha_in",
    "Fecha.de.término.dd.mm.aa"                : "fecha_ter",
    "Viáticos"                                 : "viaticos",
    "Observaciones"                            : "observaciones"
  }, inplace = True
)

contrata_2013_2022
```

Now we have a dataframe more easy to work with, but we still have some issues about the data, lets look at the "mont_hr_ext_diur" column.

```{python}
contrata_2013_2022['mont_hr_ext_diur']
```

At first sight we can note that there is a combination of payment and hours associated with that payment, this problem is presented for all the columns that are related with extra hours, so we need to follow some steps in order to split clean those columns.

```{python}
contrata_2013_2022[["monto_hr_ext_diur","hr_ext_diur"]] = contrata_2013_2022.mont_hr_ext_diur.str.split(":", expand=True)

contrata_2013_2022[["monto_hr_ext_noct","hr_ext_noct"]] = contrata_2013_2022.mont_hr_ext_noct.str.split(":", expand=True)

contrata_2013_2022[["monto_hr_ext_fest","hr_ext_fest"]] = contrata_2013_2022.mont_hr_ext_fest.str.split(":", expand=True)


```

Now we have different columns for the salary related to extra hours, and the total of extra hours for each worker at the Macul municipality. But the format of those columns are not numeric, so we need to fix that. First, we will do it for the salary data.

```{python}
contrata_2013_2022["monto_hr_ext_diur"] = contrata_2013_2022["monto_hr_ext_diur"].replace({"No tiene" : "0",
          ",00" : ""}, regex = True)
contrata_2013_2022["monto_hr_ext_noct"] = contrata_2013_2022["monto_hr_ext_noct"].replace({"No tiene" : "0",
          ",00" : ""}, regex = True)
contrata_2013_2022["monto_hr_ext_fest"] = contrata_2013_2022["monto_hr_ext_fest"].replace({"No tiene" : "0",
          ",00" : ""}, regex = True)


contrata_2013_2022["monto_hr_ext_diur"] = pd.to_numeric(contrata_2013_2022["monto_hr_ext_diur"])
contrata_2013_2022["monto_hr_ext_noct"] = pd.to_numeric(contrata_2013_2022["monto_hr_ext_noct"])
contrata_2013_2022["monto_hr_ext_fest"] = pd.to_numeric(contrata_2013_2022["monto_hr_ext_fest"])

```

Now we can repeat the process for the extra hours data. Looking at the data the index 1503 has a problem related to the format of the data, it has been inverted, so first we need to remove that row.

```{python}
contrata_2013_2022 = contrata_2013_2022.drop(1503)
```

Then we can clean the extra hours columns.

```{python}
# day
contrata_2013_2022["hr_ext_diur"] = contrata_2013_2022["hr_ext_diur"].replace({"," : "."," hrs" : ""}, regex=True)


contrata_2013_2022["hr_ext_diur"] = pd.to_numeric(contrata_2013_2022["hr_ext_diur"])

# night
contrata_2013_2022["hr_ext_noct"] = contrata_2013_2022["hr_ext_noct"].replace({"," : "."," hrs" : ""}, regex=True)

contrata_2013_2022["hr_ext_noct"] = pd.to_numeric(contrata_2013_2022["hr_ext_noct"])

# hollidays
contrata_2013_2022["hr_ext_fest"] = contrata_2013_2022["hr_ext_fest"].replace({"," : "."," hrs" : ""}, regex=True)

contrata_2013_2022["hr_ext_fest"] = pd.to_numeric(contrata_2013_2022["hr_ext_fest"])

# Transforming NaN to zero

columns = ['hr_ext_diur', 'hr_ext_noct', 'hr_ext_fest']
contrata_2013_2022_clean = contrata_2013_2022.fillna({col: 0 for col in columns})
```

The last step in cleaning process, will be to transform the salary data in a way useful for analysis.

```{python}
# first look at the salary data
contrata_2013_2022_clean["r_bruta_mens"]
contrata_2013_2022_clean["r_liquida_mens"]

# remove the $ sign and transform to numeric

# need to improve this part
contrata_2013_2022_clean["r_bruta_mens"] = contrata_2013_2022_clean["r_bruta_mens"].str.replace({"$" : "", "." : ""}, regex=True)

contrata_2013_2022_clean["r_bruta_mens"] = pd.to_numeric(contrata_2013_2022_clean["r_bruta_mens"])

contrata_2013_2022_clean["r_bruta_mens"]

contrata_2013_2022_clean["r_liquida_mens"] = contrata_2013_2022_clean["r_liquida_mens"].str.replace({"$" : "", "." : "", "-" : ""}, regex=True)


contrata_2013_2022_clean["r_liquida_mens"] = pd.to_numeric(contrata_2013_2022_clean["r_liquida_mens"])

contrata_2013_2022_clean["r_liquida_mens"]
```

Now the salary data is in chilean pesos and can be analyzed. We will export the clean data in order to use it.

```{python}
from pathlib import Path  
filepath = Path('../data/contrata_2013_2022_clean.csv', encoding='utf-8-sig')

contrata_2013_2022_clean.to_csv(filepath)
```
